features = {
    'original_cols': [
        'srch_id',
        # 'date_time',  # not used in models
        'site_id',
        #     'visitor_location_country_id',
        'visitor_hist_starrating',
        'visitor_hist_adr_usd',
        'prop_country_id',
        'prop_id',
        'prop_starrating',
        'prop_review_score',
        'prop_brand_bool',
        'prop_location_score1',
        'prop_location_score2',
        'prop_log_historical_price',
        'price_usd',
        'promotion_flag',
        'srch_destination_id',
        #     'srch_length_of_stay',
        'srch_booking_window',
        #     'srch_adults_count',
        'srch_children_count',
        #     'srch_room_count',
        'srch_saturday_night_bool',
        'srch_query_affinity_score',
        'orig_destination_distance',
        'random_bool',
        #     'comp1_inv',
        #     'comp1_rate_percent_diff',
        #     'comp2_inv',
        # 'comp2_rate_percent_diff',
        #     'comp3_inv',
        # 'comp3_rate_percent_diff',  # was a bit useful but accidentally removed
        #     'comp4_inv',
        #     'comp4_rate_percent_diff',
        #     'comp5_inv',
        # 'comp5_rate_percent_diff',
        #     'comp6_inv',
        #     'comp6_rate_percent_diff',
        #     'comp7_inv',
        #     'comp7_rate_percent_diff',
        #     'comp8_inv',
        #     'comp8_rate_percent_diff',
    ],

    'booking_date_features': [
        'date_time_ordinal',
        #     'booking_time_minute',
        #     'booking_time_hour',
        #     'booking_time_morning',
        #     'booking_time_afternoon',
        #     'booking_time_evening',
        #     'booking_time_late_evening',
        #     'booking_time_night',
        #     'booking_time_work_hour',
        #     'booking_time_lunch',
        #     'booking_time_day',
        #     'booking_time_is_month_start',
        #     'booking_time_is_month_end',
        #     'booking_time_dow',
        #     'booking_time_is_weekend',
        #     'booking_time_doy',
        #     'booking_time_week',
        #     'booking_time_week_mid_summer_index',
        #     'booking_time_month',
        #     'booking_time_days_in_month',
        #     'booking_time_quarter',
        #     'booking_time_is_quarter_start',
        #     'booking_time_is_quarter_end',
        #     'booking_time_season_num',
        #     'booking_time_year',
        #     'booking_time_is_year_start',
        #     'booking_time_is_year_end',
        #     'booking_time_week_id',
        #     'booking_time_day_sin',
        #     'booking_time_day_cos',
        #     'booking_time_month_sin',
        #     'booking_time_month_cos',
        #     'booking_time_quarter_sin',
        #     'booking_time_quarter_cos',
        #     'booking_time_week_sin',
        #     'booking_time_week_cos',
        #     'booking_time_dow_sin',
        #     'booking_time_dow_cos',
        #     'booking_time_doy_sin',
        #     'booking_time_doy_cos',
        #     'booking_time_season_num_sin',
        #     'booking_time_season_num_cos',
        #     'holidays_during_booking',
    ],

    'prop_location_score_features': [
        'prop_location_score_diff',
        #     'prop_location_score_diff_7',
        'prop_location_score_sum',
        #     'prop_location_score_sum_7',
        'prop_location_score_mul',
        'prop_location_score_diff_log',
        'prop_location_score_sum_log',
        'prop_location_score_mul_log',
    ],

    'competitor_features': [
        #     'higher_price_than_expedia',
        #     'lower_price_than_expedia',
        #     'same_price_as_expedia',
        #     'comp_num_avail',
        # 'ratio_of_comp_with_higher_price_than_expedia',
        'ratio_of_comp_with_lower_price_than_expedia',
        #     'comp1_rate_percent_diff_signed',
        #     'comp2_rate_percent_diff_signed',
        #     'comp3_rate_percent_diff_signed',
        #     'comp4_rate_percent_diff_signed',
        'comp5_rate_percent_diff_signed',
        #     'comp6_rate_percent_diff_signed',
        #     'comp7_rate_percent_diff_signed',
        'comp8_rate_percent_diff_signed',

        #  'comp1_rate_percent_diff_log_2',
        #     'comp1_rate_percent_diff_log_10',
        #  'comp2_rate_percent_diff_log_2',
        #     'comp2_rate_percent_diff_log_10',
        #  'comp3_rate_percent_diff_log_2',
        #     'comp3_rate_percent_diff_log_10',
        #  'comp4_rate_percent_diff_log_2',
        #     'comp4_rate_percent_diff_log_10',
        #  'comp5_rate_percent_diff_log_2',
        #     'comp5_rate_percent_diff_log_10',
        #  'comp6_rate_percent_diff_log_2',
        #     'comp6_rate_percent_diff_log_10',
        #  'comp7_rate_percent_diff_log_2',
        #     'comp7_rate_percent_diff_log_10',
        #  'comp8_rate_percent_diff_log_2',
        #     'comp8_rate_percent_diff_log_10',
    ],

    'price_features': [
        # 'price_per_day',
        #     'price_per_trip',

        #     'price_usd_pow_0.33',
        #     'price_usd_pow_0.5',
        #     'price_usd_pow_2',
        #     'price_usd_log_2',
        # 'price_usd_log_10',
        #     'price_usd_log_2.72',
        #     'price_usd_reciprocal',

        #     'visitor_hist_adr_usd_pow_0.33',
        # 'visitor_hist_adr_usd_pow_0.5',
        #     'visitor_hist_adr_usd_pow_2',
        #     'visitor_hist_adr_usd_log_2',
        #     'visitor_hist_adr_usd_log_10',
        #     'visitor_hist_adr_usd_log_2.72',
        #     'visitor_hist_adr_usd_reciprocal',

        'prop_log_historical_price_pow_0.33',
        #     'prop_log_historical_price_pow_0.5',
        #     'prop_log_historical_price_pow_2',
        #     'prop_log_historical_price_log_2',
        'prop_log_historical_price_log_10',
        #     'prop_log_historical_price_log_2.72',
        'prop_log_historical_price_reciprocal',

        #     'price_per_trip_pow_0.33',
        #     'price_per_trip_pow_0.5',
        #     'price_per_trip_pow_2',
        #     'price_per_trip_log_2',
        #     'price_per_trip_log_10',
        #     'price_per_trip_log_2.72',
        #     'price_per_trip_reciprocal',

        'price_diff_to_usr_hist',
        'price_ratio_to_usr_hist',
        'price_diff_to_place_hist_price',
        #     'place_hist_price_diff_usr_hist',
        # 'price_per_day_diff_to_usr_hist',
        # 'price_per_day_ratio_to_usr_hist',
        # 'price_per_trip_diff_to_usr_hist',
        # 'price_per_trip_ratio_to_usr_hist',
        # 'price_per_day_diff_to_place_hist_price',
        # 'price_per_trip_diff_to_place_hist_price',

        'price_usd_log10_norm_by_srch_id',
    ],

    'star_features': ['prop_star_usr_hist_diff',
                      # 'prop_review_usr_hist_diff',
                      'prop_starrating_bonus_chain',
                      'prop_star_review_sum',
                      'prop_star_review_diff',
                      'prop_star_review_min',
                      'prop_star_review_max',
                      'prop_star_review_mean',
                      # 'prop_starrating_monotonic'
                      'prop_starrating_norm_by_srch_id',
                      ],

    'price_star_features': ['price_per_star',
                            'price_per_review_score',
                            #                        'usr_price_per_star',
                            #                        'price_per_star_diff_with_usr',
                            #                        'price_per_review_diff_with_usr',
                            'price_per_star_log_10',
                            'price_per_review_score_log_10',
                            # 'usr_price_per_star_log_10',
                            ],

    'trip_detail_features': [
        # 'travel_inside',
        #     'trans_ocean',
        # 'booking_weeks_ahead',
        #     'booking_months_ahead',
        'len_of_stay_to_booking_ahead_ratio',
        #     'len_of_stay_to_booking_ahead_diff',
        #     'srch_length_of_stay_in_weeks',
        #     'date',
        #     'trip_start_date',
        #     'trip_end_date',
        #     'holidays_during_trip',
        #     'business_trip',
        # 'holiday_during_trip',
        # 'holiday_during_booking',
        'children_per_adult',
        #     'total_people',
        'people_per_room',
        # 'separate_children_room',

        'trip_start_date',
        # 'trip_start_date_week',
        # 'trip_start_date_week_mid_summer_index',
        # 'trip_start_date_month',
        # 'trip_start_date_days_in_month',
        #  'trip_start_date_quarter',
        #  'trip_start_date_is_quarter_start',
        #  'trip_start_date_is_quarter_end',
        # 'trip_start_date_season_num',
        #  'trip_start_date_year',
        #  'trip_start_date_is_year_start',
        #  'trip_start_date_is_year_end',
        # 'trip_start_date_week_id',

        # 'trip_end_date_week',
        'trip_end_date_week_mid_summer_index',
        # 'trip_end_date_month',
        # 'trip_end_date_days_in_month',
        # 'trip_end_date_quarter',
        # 'trip_end_date_is_quarter_start',
        # 'trip_end_date_is_quarter_end',
        # 'trip_end_date_season_num',
        # 'trip_end_date_year',
        # 'trip_end_date_is_year_start',
        # 'trip_end_date_is_year_end',
        # 'trip_end_date_week_id',
    ],

    'aggregate_features': [
        'price_index_per_srch_id',
        'price_index_per_srch_destination_id',
        'price_index_per_prop_id',
        #     'mean_click_bool_per_prop_id',
        #     'mean_booking_bool_per_prop_id',
        #     'mean_srch_query_affinity_score',
        #     'mean_position_per_prop_id',
    ],

    'uncategorized_features': [
        #     'was_sold_in_that_period',
        'srch_query_affinity_score_prob'
    ],

    ##### AGGREGATION FEATURES #####
    'per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter': [
        #     'mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'median_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'min_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'max_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_trip_start_date_quarter'],

    'per_visitor_location_country_id_per_prop_id': [
        'mean_price_per_day_per_visitor_location_country_id_per_prop_id',
        'median_price_per_day_per_visitor_location_country_id_per_prop_id',
        #     'min_price_per_day_per_visitor_location_country_id_per_prop_id',
        'max_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_id',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_id',

        #     'mean_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        #     'median_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        #     'min_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        #     'max_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        #     'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        #     'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_id_per_trip_start_date_quarter'
    ],

    'per_day_per_prop_id_per_trip_start_date_quarter': [
        'mean_price_per_day_per_prop_id_per_trip_start_date_quarter',
        #     'median_price_per_day_per_prop_id_per_trip_start_date_quarter',
        #     'min_price_per_day_per_prop_id_per_trip_start_date_quarter',
        # 'max_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_mean_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_mean_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_median_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_median_price_per_day_per_prop_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_prop_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_prop_id_per_trip_start_date_quarter'
    ],

    'per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter': [
        #     'mean_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'median_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'min_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        #     'max_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_mean_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_median_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_median_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_prop_id_per_srch_room_count_per_trip_start_date_quarter'
    ],

    'per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2': [
        'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        #     'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        #     'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_location_score2'
    ],

    'price_per_day_per_visitor_location_country_id_per_prop_starrating': [
        'mean_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'median_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        #  'min_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        #  'max_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_starrating',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_starrating'
    ],

    'per_srch_destination_id_per_srch_room_count_per_prop_review_score': [
        #     'mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        #  'median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        'min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        #  'max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        # 'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        # 'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_review_score'
    ],

    'per_day_per_srch_destination_id_per_trip_start_date_quarter': [
        #     'mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        #  'median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        #  'min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        #  'max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        #     'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        #  'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter'
    ],

    'per_day_per_prop_country_id': [
        #     'mean_price_per_day_per_prop_country_id',
        #  'median_price_per_day_per_prop_country_id',
        'min_price_per_day_per_prop_country_id',
        # 'max_price_per_day_per_prop_country_id',
        #  'price_per_day_diff_to_mean_price_per_day_per_prop_country_id',
        #  'price_per_day_rel_diff_to_mean_price_per_day_per_prop_country_id',
        # 'price_per_day_diff_to_median_price_per_day_per_prop_country_id',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_prop_country_id',
        # 'price_per_day_diff_to_min_price_per_day_per_prop_country_id',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_country_id',
        'price_per_day_diff_to_max_price_per_day_per_prop_country_id',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_prop_country_id'
    ],

    'per_visitor_location_country_id_per_prop_review_score': [
        'mean_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'median_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        #  'min_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        #  'max_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        #  'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_review_score',
        #  'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_review_score'
    ],

    'per_visitor_location_country_id_per_srch_destination_id': [
        # 'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        #  'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        #  'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        #  'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        # 'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id'
    ],

    'per_prop_id': [
        'mean_price_per_day_per_prop_id',
        'median_price_per_day_per_prop_id',
        'min_price_per_day_per_prop_id',
        'max_price_per_day_per_prop_id',
        'price_per_day_diff_to_mean_price_per_day_per_prop_id',
        'price_per_day_rel_diff_to_mean_price_per_day_per_prop_id',
        'price_per_day_diff_to_median_price_per_day_per_prop_id',
        'price_per_day_rel_diff_to_median_price_per_day_per_prop_id',
        'price_per_day_diff_to_min_price_per_day_per_prop_id',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_id',
        'price_per_day_diff_to_max_price_per_day_per_prop_id',
        'price_per_day_rel_diff_to_max_price_per_day_per_prop_id'
    ],

    'per_day_per_srch_destination_id_per_prop_review_score': [
        #     'mean_price_per_day_per_srch_destination_id_per_prop_review_score',
        #  'median_price_per_day_per_srch_destination_id_per_prop_review_score',
        'min_price_per_day_per_srch_destination_id_per_prop_review_score',
        'max_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_prop_review_score',
        #  'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_prop_review_score',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_prop_review_score'
    ],

    # 'per_trip_start_date_month': [
    #     #     'mean_price_per_day_per_trip_start_date_month',
    #     #  'median_price_per_day_per_trip_start_date_month',
    #     #  'min_price_per_day_per_trip_start_date_month',
    #     #  'max_price_per_day_per_trip_start_date_month',
    #     #  'sum_price_per_day_per_trip_start_date_month',
    #     # 'price_per_day_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'price_per_day_rel_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_rel_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_rel_diff_to_mean_price_per_day_per_trip_start_date_month',
    #     #  'price_per_day_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'price_per_day_rel_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_rel_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_rel_diff_to_median_price_per_day_per_trip_start_date_month',
    #     #  'price_per_day_diff_to_min_price_per_day_per_trip_start_date_month',
    #     # 'price_per_day_rel_diff_to_min_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_diff_to_min_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_rel_diff_to_min_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_diff_to_min_price_per_day_per_trip_start_date_month',
    #     # 'prop_historical_price_rel_diff_to_min_price_per_day_per_trip_start_date_month',
    #     # 'price_per_day_diff_to_max_price_per_day_per_trip_start_date_month',
    #     # 'price_per_day_rel_diff_to_max_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_diff_to_max_price_per_day_per_trip_start_date_month',
    #     #  'visitor_hist_adr_usd_rel_diff_to_max_price_per_day_per_trip_start_date_month',
    #     # 'prop_historical_price_diff_to_max_price_per_day_per_trip_start_date_month',
    #     #  'prop_historical_price_rel_diff_to_max_price_per_day_per_trip_start_date_month'
    # ],

    # 'per_day_per_trip_start_date_quarter': [
    #     #     'mean_price_per_day_per_trip_start_date_quarter',
    #     #  'median_price_per_day_per_trip_start_date_quarter',
    #     #  'min_price_per_day_per_trip_start_date_quarter',
    #     #  'max_price_per_day_per_trip_start_date_quarter',
    #     #  'sum_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     # 'price_per_day_rel_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_rel_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     # 'prop_historical_price_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     # 'prop_historical_price_rel_diff_to_mean_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_rel_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_rel_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'prop_historical_price_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'prop_historical_price_rel_diff_to_median_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_rel_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_rel_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     #  'prop_historical_price_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     # 'prop_historical_price_rel_diff_to_min_price_per_day_per_trip_start_date_quarter',
    #     # 'price_per_day_diff_to_max_price_per_day_per_trip_start_date_quarter',
    #     #  'price_per_day_rel_diff_to_max_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_diff_to_max_price_per_day_per_trip_start_date_quarter',
    #     #  'visitor_hist_adr_usd_rel_diff_to_max_price_per_day_per_trip_start_date_quarter',
    #     #  'prop_historical_price_diff_to_max_price_per_day_per_trip_start_date_quarter',
    #     #  'prop_historical_price_rel_diff_to_max_price_per_day_per_trip_start_date_quarter'
    # ],

    'target_features': [
        'book_per_click',
        'booking_prob_train',
        'click_prob_train',
    ],

    'per_day_per_srch_destination_id': [
        'mean_price_per_day_per_srch_destination_id',
        'median_price_per_day_per_srch_destination_id',
        'min_price_per_day_per_srch_destination_id',
        'max_price_per_day_per_srch_destination_id',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id',
        'price_per_day_diff_to_min_price_per_day_per_srch_destination_id',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id'
    ],

    'per_srch_destination_id_per_prop_starrating': [
        # 'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_starrating',

        # 'mean_price_per_day_per_srch_destination_id_per_prop_starrating',
        'median_price_per_day_per_srch_destination_id_per_prop_starrating',
        'min_price_per_day_per_srch_destination_id_per_prop_starrating',
        'max_price_per_day_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_starrating',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_prop_starrating',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_prop_starrating',
        # 'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_prop_starrating',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_prop_starrating',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_prop_starrating'
    ],

    'per_day_per_prop_country_id_per_trip_start_date_quarter': [
        # 'mean_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'median_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'min_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'max_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_mean_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_median_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_prop_country_id_per_trip_start_date_quarter'
    ],

    'per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter': [
        'mean_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'median_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        'min_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'max_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_median_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_max_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_prop_country_id_per_srch_room_count_per_trip_start_date_quarter'
    ],

    'per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating': [
        # 'mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        # 'max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        # 'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        # 'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_starrating'
    ],

    'per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter': [
        #     'mean_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'median_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'min_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'max_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_country_id_per_trip_start_date_quarter'
    ],

    'per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score': [
        # 'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score'
    ],

    # 'per_day_per_trip_start_date_month_per_srch_destination_id': [
    #     # 'mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'sum_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_rel_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_rel_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_rel_diff_to_mean_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_rel_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_rel_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_rel_diff_to_median_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     ####'price_per_day_rel_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_rel_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_rel_diff_to_min_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'price_per_day_rel_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'visitor_hist_adr_usd_rel_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id',
    #     # 'prop_historical_price_rel_diff_to_max_price_per_day_per_trip_start_date_month_per_srch_destination_id'
    # ],

    'per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score': [
        'mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        ### 'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_review_score'
    ],

    'per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score': [
        # 'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score',
        # 'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_prop_review_score'
    ],

    'per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating': [
        # 'mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        # 'median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        # 'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        # 'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        # 'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_starrating'],

    'per_day_per_visitor_location_country_id_per_prop_country_id': [
        'mean_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'median_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        # 'min_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'max_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_country_id',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_country_id'],

    'per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter': [
        # 'mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        # 'median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        # 'min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        # 'max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        # 'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        # 'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_srch_destination_id_per_trip_start_date_quarter'
    ],

    'per_day_per_prop_location_score2_round': [
        'mean_price_per_day_per_prop_location_score2_round',
        'median_price_per_day_per_prop_location_score2_round',
        'min_price_per_day_per_prop_location_score2_round',
        'max_price_per_day_per_prop_location_score2_round',
        'price_per_day_diff_to_mean_price_per_day_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_mean_price_per_day_per_prop_location_score2_round',
        'price_per_day_diff_to_median_price_per_day_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_median_price_per_day_per_prop_location_score2_round',
        'price_per_day_diff_to_min_price_per_day_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_min_price_per_day_per_prop_location_score2_round',
        'price_per_day_diff_to_max_price_per_day_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_max_price_per_day_per_prop_location_score2_round'
    ],

    'per_day_per_visitor_location_country_id_per_prop_location_score2_round': [
        'mean_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'median_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'min_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'max_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_mean_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_median_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_min_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_max_price_per_day_per_visitor_location_country_id_per_prop_location_score2_round'
    ],

    'per_day_per_srch_destination_id_per_prop_location_score2_round': [
        'mean_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'median_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'min_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'max_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_prop_location_score2_round'
    ],

    'per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round': [
        'mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_trip_start_date_quarter_per_prop_location_score2_round'
    ],

    'prop_starrating_per_srch_id': [
        'mean_prop_starrating_per_srch_id',
        'median_prop_starrating_per_srch_id',
        'min_prop_starrating_per_srch_id',
        'max_prop_starrating_per_srch_id',
        'prop_starrating_diff_to_mean_prop_starrating_per_srch_id',
        'prop_starrating_rel_diff_to_mean_prop_starrating_per_srch_id',
        'prop_starrating_diff_to_median_prop_starrating_per_srch_id',
        'prop_starrating_rel_diff_to_median_prop_starrating_per_srch_id',
        'prop_starrating_diff_to_min_prop_starrating_per_srch_id',
        'prop_starrating_rel_diff_to_min_prop_starrating_per_srch_id',
        'prop_starrating_diff_to_max_prop_starrating_per_srch_id',
        'prop_starrating_rel_diff_to_max_prop_starrating_per_srch_id'
    ],

    'prop_location_score2_per_srch_id': [
        'mean_prop_location_score2_per_srch_id',
        'median_prop_location_score2_per_srch_id',
        'min_prop_location_score2_per_srch_id',
        'max_prop_location_score2_per_srch_id',
        'prop_location_score2_diff_to_mean_prop_location_score2_per_srch_id',
        'prop_location_score2_rel_diff_to_mean_prop_location_score2_per_srch_id',
        'prop_location_score2_diff_to_median_prop_location_score2_per_srch_id',
        'prop_location_score2_rel_diff_to_median_prop_location_score2_per_srch_id',
        'prop_location_score2_diff_to_min_prop_location_score2_per_srch_id',
        'prop_location_score2_rel_diff_to_min_prop_location_score2_per_srch_id',
        'prop_location_score2_diff_to_max_prop_location_score2_per_srch_id',
        'prop_location_score2_rel_diff_to_max_prop_location_score2_per_srch_id'
    ],

    'prop_location_score1_per_srch_id': [
        'mean_prop_location_score1_per_srch_id',
        'median_prop_location_score1_per_srch_id',
        'min_prop_location_score1_per_srch_id',
        'max_prop_location_score1_per_srch_id',
        'prop_location_score1_diff_to_mean_prop_location_score1_per_srch_id',
        'prop_location_score1_rel_diff_to_mean_prop_location_score1_per_srch_id',
        'prop_location_score1_diff_to_median_prop_location_score1_per_srch_id',
        'prop_location_score1_rel_diff_to_median_prop_location_score1_per_srch_id',
        'prop_location_score1_diff_to_min_prop_location_score1_per_srch_id',
        'prop_location_score1_rel_diff_to_min_prop_location_score1_per_srch_id',
        'prop_location_score1_diff_to_max_prop_location_score1_per_srch_id',
        'prop_location_score1_rel_diff_to_max_prop_location_score1_per_srch_id'
    ],

    'prop_review_score_per_srch_id': [
        'mean_prop_review_score_per_srch_id',
        'min_prop_review_score_per_srch_id',
        'max_prop_review_score_per_srch_id',
        'prop_review_score_diff_to_mean_prop_review_score_per_srch_id',
        'prop_review_score_rel_diff_to_mean_prop_review_score_per_srch_id',
        'prop_review_score_diff_to_min_prop_review_score_per_srch_id',
        'prop_review_score_rel_diff_to_min_prop_review_score_per_srch_id',
        'prop_review_score_diff_to_max_prop_review_score_per_srch_id',
        'prop_review_score_rel_diff_to_max_prop_review_score_per_srch_id'
    ],

    'price_usd_per_srch_id': [
        'mean_price_usd_per_srch_id',
        'median_price_usd_per_srch_id',
        'min_price_usd_per_srch_id',
        'max_price_usd_per_srch_id',
        'price_usd_diff_to_mean_price_usd_per_srch_id',
        'price_usd_rel_diff_to_mean_price_usd_per_srch_id',
        'price_usd_diff_to_median_price_usd_per_srch_id',
        'price_usd_rel_diff_to_median_price_usd_per_srch_id',
        'price_usd_diff_to_min_price_usd_per_srch_id',
        'price_usd_rel_diff_to_min_price_usd_per_srch_id',
        'price_usd_diff_to_max_price_usd_per_srch_id',
        'price_usd_rel_diff_to_max_price_usd_per_srch_id'
    ],

    'per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round': [
        'mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_mean_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_median_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_min_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round',
        'price_per_day_rel_diff_to_max_price_per_day_per_srch_destination_id_per_srch_room_count_per_prop_location_score2_round'
    ],

    'service_cols': [
        # 'index'
    ]
}

CAT_FEATURES = ['srch_id',
                'site_id',
                'visitor_location_country_id',
                'prop_country_id',
                'prop_id',
                'srch_destination_id',
                'week_id',
                'trip_start_date_week',
                'trip_start_date_week_mid_summer_index',
                'trip_start_date_week_id',
                'trip_end_date_week',
                'trip_end_date_week_mid_summer_index',
                'trip_end_date_week_id',
                'season_num',
                'day',
                'month',
                'year',
                'quarter',
                'week',
                'dow',
                'holiday_during_trip',
                'holiday_during_booking'
                ]

BOOL_COLS = ['prop_brand_bool',
             'promotion_flag',
             'srch_saturday_night_bool',
             'random_bool',
             'was_sold_in_that_period', 'trans_ocean',
             'travel_inside', 'business_trip',
             'separate_children_room']
